export const HAWK_FAILED_TO_CREATE_TRANSACTION_CHECKS = {
  code: 101001,
  description: 'HAWK_FAILED_TO_CREATE_TRANSACTION_CHECKS',
};

export const HAWK_FAILED_TO_UPDATE_TRANSACTION_CHECKS = {
  code: 101002,
  description: 'HAWK_FAILED_TO_UPDATE_TRANSACTION_CHECKS',
};

export const HAWK_FAILED_TO_CREATE_CUSTOMER_CHECKS = {
  code: 101003,
  description: 'HAWK_FAILED_TO_CREATE_CUSTOMER_CHECKS',
};

export const HAWK_FAILED_TO_UPDATE_CUSTOMER_CHECKS = {
  code: 101004,
  description: 'HAWK_FAILED_TO_UPDATE_CUSTOMER_CHECKS',
};
